# By default, builds only for darwin and linux, which works for us since FlowGo does not support
# Windows builds. We also can only build on amd64 architectures since all others are also not
# supported at the moment.
builds:
  - id: dps-client
    binary: dps-client
    goarch:
      - amd64
    main: ./cmd/flow-dps-client

  - id: dps-indexer
    binary: dps-indexer
    goarch:
      - amd64
    main: ./cmd/flow-dps-indexer

  - id: dps-server
    binary: dps-server
    goarch:
      - amd64
    main: ./cmd/flow-dps-server

  - id: dps-live
    binary: dps-live
    goarch:
      - amd64
    main: ./cmd/flow-dps-live
    flags:
      - -tags=relic

  - id: rosetta-server
    binary: rosetta-server
    goarch:
      - amd64
    main: ./cmd/flow-rosetta-server
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
